package main

import (
	"bytes"
	"fmt"
)

// "regexp"
// "strconv"

func getYesAnswers(form string) int {
	answers := [26]bool{}
	for i := 0; i < 26; i++ {
		answers[i] = false
	}
	for i := 0; i < len(form); i++ {
		answers[form[i]-'a'] = true
	}
	count := 0
	for i := 0; i < len(answers); i++ {
		if answers[i] {
			count++
		}
	}
	return count
}

func countYesAnswers(forms []string) {
	count := 0
	for _, form := range forms {
		count += getYesAnswers(form)
	}
	fmt.Printf("You have a total of %d Yes answers\n", count)
}

func solveDay06Example() {
	forms := []string{
		"abc",
		"abc",
		"abac",
		"aaaa",
		"b",
	}
	countYesAnswers(forms)
}

func solveDay06Part1() {
	forms := getDay06DataPart1()
	countYesAnswers(forms)
}

func intersectBytes(bytesA []byte, bytesB []byte) []byte {
	res := []byte{}
	for _, a := range bytesA {
		if bytes.Contains(bytesB, []byte{a}) {
			res = append(res, a)
		}
	}
	// fmt.Printf("intersect(%s, %s) = %s\n", string(bytesA), string(bytesB), string(res))
	return res
}

func intersectStrings(strA string, strB string) string {
	return string(intersectBytes([]byte(strA), []byte(strB)))
}

func countAllYesAnswers(forms []string) int {
	commonAnswer := []byte(forms[0])
	for i := 1; i < len(forms); i++ {
		commonAnswer = intersectBytes(commonAnswer, []byte(forms[i]))
	}
	return len(commonAnswer)
}

func solveDay06Part2() {
	forms := getDay06DataPart2()

	count := 0
	groupForms := []string{}
	for _, form := range forms {
		if form == "" {
			// fmt.Printf("working with a group of forms  %v\n", groupForms)
			count += countAllYesAnswers(groupForms)
			groupForms = []string{}
		} else {
			groupForms = append(groupForms, form)
		}
	}
	count += countAllYesAnswers(groupForms)
	fmt.Printf("You have a total of %d answers for all your groups\n", count)

}

// ----------
func getDay06DataPart1() []string {
	return []string{
		"xavuavxxavsiyavx",
		"efokjptizdcwmqnuhqgfdvurtnjwpichxktaqkcunfzpmydiwjsh",
		"mzbgtmgrlvgehgpbzncagkijyu",
		"ahynbmqljzpwxokcfrtsgeudxwzcmdhkrjnupegqlyoaftfjnurhzoqmgwacxdlypkteqwrjxahtlnzcfdouepmkgyezpqxfcmgrnhylukwajotd",
		"jrxcnyadsgbtpvozesecpytarvdzjgbycsfzgtedarbjvptsgejyzcdbvpraygtbvzredpacjs",
		"nnsnn",
		"mgfbmfg",
		"xfjengypubwisroqb",
		"hcnkeawlbfsotwocmsbefvlpacwyseblorflosebfcw",
		"dixstroacjbygqpewvkmdcpbnfqsgxvaikwujtr",
		"uuvk",
		"vpuzognlmhxvfgkdnspqjpvzogntyrajpngbcivw",
		"bipitb",
		"uvqldphgedpgfh",
		"gmmgfsmgmgqgm",
		"gtkmwkcgmsvdagmksapmkupgtgekrbimhj",
		"hknejxwjnjanojvwnbujnic",
		"vkzmgdbzbgvdbzdgvgbvdzzdbvg",
		"sedcuhaxyeqbs",
		"ckysjbmawxpedqovilqcuxpvajwmfyko",
		"xcvxhevkcvfxcywcvfxcjxv",
		"wetaojdqkipkyedwuprqasttadubqkflpyanpslwqdtikzmgacdpkxq",
		"akdhyogxqfktnyzhxoaqfgwd",
		"dbnezgquatrmewnqlzdjcgbhnzdebjgql",
		"aoxjcbpzisfmkewqlngduytvdifaqevcgyukztjwpmbsxonr",
		"grptdznpzctgolskr",
		"kvyjetqndhfyetdvnqkfsvwdpxqgeianfk",
		"tmyreouwntorwnaeumytsewnmzypoemosthywnmjtkevnqcbdiwoxy",
		"zstlfpnavdwyicuhbtwlpczyhunivdaovnuwycptldhzaipcyhdwtuianlvz",
		"kwvaunqjryxtpzwflvuzhnxmecokiyjts",
		"kjcqzvhseafqgfmhsekjctv",
		"tcpvqdrnghflmjoxawemdplxfqnovejsgazcrhqxkhmvbpdoegnfjrlac",
		"ixzcphsklygsxioyzcahkl",
		"stjxfncpdegihznsoylvrujnskwnsqmbnajbs",
		"pxatigolezvxkbvuitegwmogvijtmysxoesvnxeqjogtiksoxevgqcit",
		"otzmkhlquxwranieqdjfgmaor",
		"exzqzezeze",
		"xwzapvtqrgecjisfunkhdqefspnwtkijacuhdgrzzqjkasgnferutdwhcbpirwapenikhdjcsqfzgubt",
		"fmjeqdaivksonrpfeljvbqdsormxhuywvtceosm",
		"zhlaoheh",
		"qnyhtezxjdvpfkcsionvchtzepkqjoisdyfxvifhcnxstzjpedoykqqsivneohjzpbdcymlgxfktsxvkpohctnjfyqezid",
		"ndzhflczfdcnhfchznd",
		"nrvderamndvu",
		"tskgvzqmunszckqgbvmnwzvmsnrygaqvcqmstinzgjlospfehmzvndxgq",
		"btlfvysaqerchkiuxtlyxhkrvbqufsecaivfturxsbayicheqlksruhcbeqktixvfayl",
		"vammvvmvmvm",
		"kkkkk",
		"ysmikquxzcyetmlxqsziu",
		"ornkorknrknokoirnonyrk",
		"qcajzosfsofdacjajoscfdjfscaeofosejac",
		"rkqghbxjdoluqbdhjkmjhbdcbtvadiehjhfdbrj",
		"nsklymutzivwmounvbpwdg",
		"sdpgvajmexuyqhcriokvjksamihwpdrcxqguyxjsevuydcamkihoqgprmjtcnqpgdhvuakfrbxyi",
		"hpoyrxfmcjldcxlpodryfmjhjhplfcrydxmo",
		"kembuivdhfipefszdhenclshdbfkdhreytjwxqgfao",
		"lblkr",
		"smtknclagppcktnslgam",
		"bfscynbfhbxklwfep",
		"yehaybeseyeyw",
		"tatanjtaptahlcat",
		"ikdqblgsmtwlvhnbkjsdicplzskbdi",
		"rctauyzbdklxvpmnwqjfeplhzdsnbmxqarwjktyfuice",
		"baababbarab",
		"iiiv",
		"ursqyqrwusyyrsuqqrsyuqursy",
		"cdgrouisocrigs",
		"vjwaiphypva",
		"yhuqbinztxgkuqxeogthpidgtmhiquxlwgxutsafqbih",
		"wmgwz",
		"gkpmdtwhnxzaoysjcevuirhoxmkyqdcwlnvgperszi",
		"oqagyglxvkqsdzbreguiwjfm",
		"nabmlpfnyvatk",
		"pupu",
		"hbivybyuvtueovyb",
		"ozqvqzon",
		"xjunwvbzdkqychfosmgre",
		"dynejxyxydqyxiyp",
		"hskfyqgtbzrvuyvqhtgbuifrskzhzjqfuyrbvstgkzvkhtsfgryqbu",
		"onsosnenoussuno",
		"zymjefdwxihdwxzyfjmieh",
		"ibbia",
		"ocagmvjjvcagmgamcjvvjcamg",
		"inhlewtdbkxmpaqrygwnkpxrhlmigtaydbqeoihnlytpwaxrbqekdmgmqabydwgterlphnkxi",
		"bjedsywlgnxmpotzpxejsongtkumzbwldlpogxznbtwmsjedtzpuonmjxlwbesgd",
		"wqfsmektuwmftqssqmtwftqmscfwtqwmsf",
		"snkpjbefqwhyrizikwrlqymjczfbevntpsqhebojfnzrkwapmsibegirdpqnjkwuzsfiqtbhfzpenwkrjs",
		"yy",
		"gsfgcshajqgs",
		"ulqbokwrjdcgpthniyxfzmeavrjbumtoxecngkdvazsfilw",
		"fwsrhjkhjrfwkskfjrhswjrhkfsw",
		"qktgsvplhhgolhgly",
		"qftenaodxkwzbwtxaqviof",
		"ugzpmhefkjkgemzusfpjhdekfjlhpmguzkxuepjgonfyhzqkuzgitlhfjep",
		"jywhzcrqaotzngembuvfsk",
		"iwhekorjgqtsdbkjgswlbqherodtiokirgdnejtxwbqhsezobksgqrajhwdti",
		"rdcoaubxhkitwsvpzygflmqnjtcnfguzdybojqvwishrlapmkxsmjnpglbkzuafqhtdoxwiycrvspgnmzlyurchxvwbojfqakidtkzdtmbslqyvxcrwnauhoijgfp",
		"kvwmmwvkkwvmkvwm",
		"htorhghtvhivhfk",
		"woxhpvfdlneziwemdcqwkdesedwuqwcadtgrbe",
		"moecdswscmbnoedsdycmeo",
		"amnqlcytodvreiwkzgfxsvfwmayqsghdcjztxeornkuilxgaifqzdvowmknlysrtceiynsxqwmafdvtklzregoc",
		"ksvejmeskmvjksmjvevhskemjekmsvj",
		"ebfkazrdgqtkjmwclykapzukinrbh",
		"oznuhklqijpmsxfcarybhyikolbjusmxqcfnzarpuzxcbwqshkyamrielnopf",
		"zlpsuawlzdspuluzsp",
		"hhkrhlhch",
		"zfugqrjipavboysaurvpzfeosigjqysrnqiejtoyupgvadfzboqryvigjzsuafpqgowivrzajsupfy",
		"mrotnsaivyxbwpiapmtxsgbyodwrwoaxsyjicpbtrfm",
		"rdlakocwumetfpjscshjuyxwgatvz",
		"wbxauycvxbwgaoveaxwnovbfwyxmvabxtiqwbsazvjpl",
		"opppp",
		"ombjurgkvcenyilxtpwaz",
		"gzjpkewnfylarinlifyawpzgkjm",
		"ymhesgwkxczrtbjnucywuetkbhnsxjrzgmuwybxgsjnhremztkc",
		"pcsxyiuvfnjbtkqwhlgzrixqnskyfwrtlgchbvjpzucvuqazjkhbxtlyrnwgifs",
		"ceeccgeecgyeh",
		"itfhrlsvgdensvhekgidlrnfnirlehsgfdvsginfeldrhvirsvdlfhegn",
		"wy",
		"jqwevpgkzhdarpazkvjqdrwhurzhvwkpaqd",
		"lsmqgjkbglmksbjqqsklgbjxm",
		"iouyxrvbqjcemzlapkovlkizemjyarbcupxzluckepmbrxivajyozijoveubxmlpykrcad",
		"tjaruhsdgypeapmetysfkivjblqd",
		"ztxyvufehdmcaqrhfgs",
		"qfvujnhtaomuvqanhfo",
		"dxwvtmlsjqurepbgnibueiqjanvlpwrzlryojfupiqvec",
		"dopjewaytmgamreytdslkgpwpeymdawotxguqyahptdxzgecwmvbohdafmpiwytge",
		"zdkalgubsqwdsazbkgluwdsuzgwlbak",
		"fibeyzxkmchfveymznaikvtyafiemkzerlfizymuk",
		"utiuguuu",
		"khqjtmswglpxnsqzgv",
		"uhkeosrgytcpbvmanqdlwjfzsingwfcorvzadktblmupejqylezdusrpwbnfmkvjcxyogatq",
		"nqlmhgrpesw",
		"hrmxwjzgwzrtpmahmrewhxywkbrnhmcirhomuvw",
		"cfpsboeiwtifcoybpxiofcpbcbpoisfpcoibf",
		"xtxxxf",
		"etvccoap",
		"gsbmanzopklywzorpislaqbnmywgawbgczsdxlumypnohwtmkgobyaslnzjppmjlbsonkfwgtzay",
		"upqwyiagtonfvrskdpkvuwoqfaiygsnmtxrunorfgkpiyasqctzwvhkbwpyrniohgufqsvatpfqgsyuhnovktirwja",
		"egkzlwjdszermjwklkaelwjzoq",
		"efmclagdkwhqxrosntzvibmdhlqfabcrwsgxonizvktdhbqlnftivxwapoczskrgm",
		"oxsedblzsblxlrfax",
		"tvvtavatgpmosjtv",
		"ltgeutudodtuoatud",
		"ycsajeisghikbpmr",
		"bjfohqiwcpdlzeysr",
		"ghcenrzqksifdckwsgdnerfziqiebsrncqmfk",
		"idbjyxctlgpwaswgiypblsacjuxd",
		"ivnkjswbbkkrbkblc",
		"hbmocfrualurlfbmocha",
		"mtvwqhagwtxdcuen",
		"bmdarywjmapexakfgubhijavvlmcia",
		"jeaposhgqcblxitkrzynaordjqiglcnpvekthsbzyjhtrkqynszelcoiabpgjkftnvbgyqploaicsehzr",
		"qqtvtz",
		"qidvuouohvqibdudivqooivduqvidqou",
		"xjlbhrsnpatqsavnktzbuldprxhgxswnpftrehlymisahprlxnctz",
		"axqniaciqnxxqianaxnrqiqxnia",
		"tbuicahrbanvchurtigrtbwaihclu",
		"jylfirgmsxlgfmxjrixgmklqtfrwjgxmlsfjr",
		"ayunwcgjgmcyngdtvfioexhysbgylngqyc",
		"neyazrtkxjhbgyxjzqknb",
		"diljtqgqwsnyuabxqsfhuzv",
		"qzpjzjqpqpgzthjqfzlpjcydxsn",
		"sbkrcjleytuidwwcbtiljyedmsugkzubetwdyikjcsllwbdieutjkcys",
		"cccct",
		"pdglkmircznxjshwytqikqrzgyxtdnjswmphclpgihtyjczwdlsqrkxnm",
		"ysjysjffjsysjpy",
		"ccac",
		"fjaounzyrckuqzfontkrajyauoyjknrzf",
		"adgezcjtmlwbnkxspzlkjswmgabtcenpxdwedpgjnmlzibkasxctbkcfsemlqzujnxtgwadp",
		"xrdzvqcyawstvztcaqyr",
		"ppwhpf",
		"syzmiglqpmnh",
		"qwkysudhalmyktykckyykm",
		"napugxjpjnuxgajxpaungxgjnapujnpxaug",
		"xcwklzsdouvejphwvecjukzhpsnluzksblpwigjchvszkwpncyudlvhfj",
		"mazvxenotrbjpsgxabenjzrgtmocpsv",
		"amkxogyllkmyxgoayagkoxlmawykgxlmogxayomkl",
		"euqjneijrqnwqnjeenjqqejn",
		"qmicprpc",
		"mhfelurtibxzgprcigefthzmbulxbehzitgmxflruuxgrmzibtelhfrzfluixbtmegh",
		"trwqtzt",
		"yjbcohwjueqzodyk",
		"tyroqsxepnbfckhuazjdwvmglibyjcgxmurontvhspekwqildzsvtmwnbighlpxeyokjurzqcdblprtoqjwnmyuxvdzkeisgch",
		"mrwtbtrmbwwtmrbrmtewbtwmbr",
		"jlwridrwibjtiwre",
		"czczzwuszzeg",
		"gxqrucimkozhpqfvbinsyiqlwdgtje",
		"wyzjqgdihbxarlwcivxtmaojgbzhpxzuwgjrabkhfidihsaezxgqnybjw",
		"jtairkfsvghze",
		"uujuuu",
		"epbvkzsoyqlrifatwchtfzwlivkhsrbceoqpaywzcqpotkrhfliavbyeswvgeufcbopsqymritkalhz",
		"vkaldbmyewircxvlibuedgamylysiabjdkvme",
		"nwhqcojkpgvfatderylibxzhgnoiclkaebtpdfjvmzywx",
		"gafbqnxstirzvoheydmlpwjhqrukwtozblfyasdxvmnpgei",
		"abpzeddapzbwcbdnzapj",
		"uhonmp",
		"yofngramnnnmn",
		"zguhotqnvkepfyabrokwtbzaqfyenkonyqtbzefa",
		"inbtkepjylqdfxczmoauwmzolcwaxfnbditkejpuqyzjyoifdkmcaupenbtwxlq",
		"yuzrirubyiyiur",
		"otdbszvjhecrkiypnydmovicrbzfkeshqng",
		"efce",
		"orbzuiszurwbbecjrkzupirlznubxbtragfdyqz",
		"fpjpfrdfprfpwc",
		"rklcfnnflck",
		"lisliikiisv",
		"awuhgmbjznsiqycker",
		"yyvmpduok",
		"jeionpfgkvxdmrzlycdiblznsykpuxwqfm",
		"mlykavvmkaaqvrkdmvkmiazrmkdvaq",
		"uyljahgbxsvczpkdqrowfntemi",
		"xjhaitwlozdpcbvdvnzjxblpcahoiwtxbwdolatjhvczip",
		"spohauibtipsatqnozlxvub",
		"vuzffchzzf",
		"almqujgzovhyfkbwtindrezvskmgitqyweoldjufranbhjrkeqfanmvoiwblzdthguy",
		"yyyyy",
		"fsqxhnbtcdybhkqnvxdwsqsdnxihbm",
		"ccvipwcqpxrkjc",
		"cbsfeonkqthadzimpwygwkybvhdsnaztcgefpqomdipbljsqxfecakmtyoghnwz",
		"ocxiztfwdjhaepyqu",
		"pbyzfvqrpqzvf",
		"pppr",
		"fgjmghxcguivrnzdwxhmqlgf",
		"lypffpylnpylwafleupfy",
		"rxyzatojxvfinbxlfkucbqxlx",
		"rkixwfkmkkmybfvkqg",
		"macdvsjophnzixyukwglqefuhkdzsyecoixjpgqvanlfwtmnszgjudxpfchoameiwrqylkvhgkswmlvjyufeipaxnoczdq",
		"hkvtprgxommxitpvkgdrhomphkortnigvkvtprlhmogdkmverqtohgpwj",
		"krsazmfbdtxyuijhiebqjdrumadimbrjuaimjurdabajrbuicdnvm",
		"jzroasvwoomkmvofo",
		"vckphlabortktprcvabohltabrkohlcvp",
		"lbjxipi",
		"ibxswpzlgakpablwzkxskzablwpxsxapzsbwkl",
		"texidwzkyjcapndjptyzcernianarcjoiteqzdpcetbjpzavigmnd",
		"thxzfeocaqpkdrvgoyxzlkzkoxkxuzngo",
		"dqsofevyrijctbxzwkghnkjwvnobzergsihtdycqxfrobqyvzihwjsxcdfektgnoctvjeshdiwbyfngzqxkr",
		"fudzlmcrjehivqpxagnowb",
		"vokdudckkndkd",
		"txqlzrvtvxlqzrvxaqzrlttcxrzvqlqtzvxrl",
		"flnclsk",
		"agqspncoikwytuvremuyijzoltcepsaxkdvhbgf",
		"gmlyxgakyvslcdthyjrioubqmylawezy",
		"dfzvhkblgnjkvzjdfgbnlhhdknbjzfvlgjkgvnzldfbhjzkhfvgbnld",
		"jvdkxqsriorpuqvkncfgzit",
		"oqzmkjbglehuw",
		"stweunormcqdyivabxkplgihfuzjbr",
		"fiakobrucnqyjtxsvmwutcfankbwvozqjxyvqknowtacjbxyfguqboaxvykfcjtuwen",
		"lqxfvjncarmowzstsgpnhqspnyueqkqns",
		"plisi",
		"alqpdpmlycntviwgfzkeaupkxo",
		"cahvspxi",
		"dgykkydggycdkygkd",
		"ygxdtqsiralczwmfokefqeoltimdykzgwxrcasmlrzsgafxqcidkweyot",
		"ibpuxwfrnjygadlucbjmfziyklnrdxwwbqrxjdihesvyunflzfubxtylwndjrpimo",
		"ahdfaqawjycasnah",
		"klygiqmwhzubproasdhetbmfiazsqrwclvugpkugnkxpmqirhswazlb",
		"notziqodkfx",
		"gwoidjbsqownkvtoywgjxaiwoeh",
		"kcsfhggfkscgcksfpcgsfdkhsckgf",
		"lzgtrfpsxwqhiyqzovtixp",
		"mqyhlxgfnbtcvwejpsrdouziksimkqtcevpohxdygbjlzrnfuwdprugmhqkcwveixoyjbstznfl",
		"mm",
		"akmrpwutnblnamrphkwtfrpumnazwkftkwrtmpvanmjakwnsxrpt",
		"kgstyrbauzjiqfmdlrlpubyfadxmtijgswzcqkbzsfnumiadjykeltgrqqfavbdhujrglyzstkmi",
		"zvxcaxazcvavcxztwxcavzkvxzoca",
		"kyjbqhdyqgmleagqyqnlgyrvqya",
		"rkbfpejgaqunlhyhogsunxedrlkbajktzjmaugrnhblierbkgnajlehuqelbwhuragjnk",
		"pkbrlqfhlvcetzujqo",
		"dbpnjmfgzuakyqrmnapvjswgyzfecl",
		"oubxuxb",
		"ktce",
		"qooq",
		"nrdoliybfmkxbfonlytdiodbyanilfzdyinxfbrlmvbnfgwdiyls",
		"ptqryhproifcxpumwaresrhbpvrp",
		"edmfbockpuzjlmejpzldckfoubbulkamoepdzjfcwjblknodpmczufeplbzukcxvdhefjmgo",
		"sbfvdziayohutkxmcepnjgrwlqslqbthaugnxcfejkymrpvdzwio",
		"ovnuybcjzwcubyavn",
		"jlpyfemohwbympjolewhfbhpjymbwolefhmfewypjlboyjwlomhpfbe",
		"yudoticgpmswxhebimctpdhksgwavxbefuyytmhucixswdegkbp",
		"femhgtschgetcpgctschmgtacogbzt",
		"jdfzyhgnkskfmgndbypsjz",
		"qxkrsvfihxvirkqfhkxirvfqhphvuixfqrmt",
		"jwqovwjqazpjnyshjwj",
		"mekjycugokyicjjevqdzsharjxltp",
		"ageqsriyfoupknldjzbqkjhmi",
		"arqoszdiyemtlpbcukxhgtskxzcqmelhorypiuaikcwsfalhzymorqxpetnu",
		"owjoo",
		"hoqrjzemyfidakhdofikzyrjqaemamyjorkehdizqfqyajdekzmfohir",
		"rfgtpasbvquzykjkwdcasjtyvzfuqegpibtpangskbuorqyjfvzqubhzfvakospgtyjtjgvuayzfprksbq",
		"xvsetimqaglzhubopjnkrwvretjpaqgzidoulbmxhknswkxzwjmscaeulgqnpovihbrtriwnepagmhktvusxqljobztugmqkbasnzhjivrlpwoxe",
		"yawojchaoyhjwcwjcyoahocawyhj",
		"atfkezomubwghcxijmlmydqzvnpr",
		"nfajymkyakjmfoskayfjmayjvkmfti",
		"zbcgaxyjdemltdhkwsugdqgfnueqgnvd",
		"ibecmecmbtfislocxympeuibiacrepxbmckibme",
		"ednxkzblgoqwrysnaklxbrzsodqegwjyf",
		"mabnelwrzykeandpqxbmlogviuhjstf",
		"xlzoysmpdgfcabiqetrmplwsgnxcadzfhukvrqjeybo",
		"lllpl",
		"zyjuwaoodfvskqocomvrcqbh",
		"fgpcjvmbxuiwtehndpcfsgtxbnkuihadmcdgtfhbmxpuni",
		"eeap",
		"ildldldldlhd",
		"hwelutkwshulk",
		"milbjvxornlbivoxrnjmmjxivlrobnilxmovnjrb",
		"inhcdkotgssyndfwkghteicogkhdiczostn",
		"jgpmfyqskckgfyqpsmcjpyfckjgmqsgskpcqyjfmpyqsjmcfgk",
		"opbqxluhyvsknxonskvbpuqhylvnijlhyqpxukgosdb",
		"dzglxpfntnfptlqynmuvrcpzdnpk",
		"ligcsyexbdoqteducotylzjbzuyockfnbhtedmlowlyuabectdfycdrabolte",
		"hwqr",
		"utqdisoacyrjgnbvzwmhekfxpl",
		"sii",
		"ovbhcfpoauvcpteqowxkpnyjlvdismczvctogpfa",
		"qtsmhpwzqchasetf",
		"ysmvbbyvsm",
		"yjkvnlqcpgasibtexycjgqedpvnxnuygpfzhvejqdxcqwyjenxfvpzmcgu",
		"tlribvnydjfexrmpjdqsbzgcxv",
		"hnuhnnhhnhnz",
		"yvzrqpbelblejaozvmyprebrlvfyzwpbrzpyelfvzwbpyervlf",
		"rtgnjiawecpmuejcnpgtawuirm",
		"qhuybzmvpnwzceb",
		"cuijneskratyqgwxmodzhplwtqshpyzrcmokixgjbenf",
		"wrthvasmxkhvktmsarx",
		"ssp",
		"tdrvjitltdpkt",
		"mgdaqpzefbxhxfbmeadgzqcneragqjmlofxysdt",
		"cvzxwpfpxwueflxswpeftwxpf",
		"eqckjbluvodhtgcvgujlhekoidtqbbhdoltuvgkqjcevhgjcektdbuloqjdogqblchetukv",
		"hmgwcszjqpyxilwzplksghxcmyjigkiczwmlyjxshjsgxcmzhlyviwujihlsyxgmdzcw",
		"ofrubwjqkxpzaitevscmgylnbigsuetvkorzqpajxwfldncm",
		"qinkinrkqknqi",
		"jvnayiodwgdostmhzeqdpohodsbohdklfu",
		"iii",
		"ndwutoamyzbrpqsvegzbdswnrevapmgtyzdtpnymegawsvrb",
		"obwzklcynjgmezlkeyfcgwmjnicjzemnypwklgomunwqycgzkeljkcnzjsiylwpxgem",
		"nbaeiqstvdwmhjukxnjxvowhqdfabieskmuztwbnsutjqdhgevkmixaycjswbkaqmvixlhutned",
		"okcwymdgvfhlxztodygvtkmlwfxzchwcmgjhdflxotzkyvkaxyfglvwmodzchtdxcafvltwokmyzgh",
		"rejdmivaxxdamjverejvdxmarrjmedxvaedrvajmx",
		"lkqgnclnckglkgcsnwklnhcglcgkn",
		"upnosleizpnlszweesjpdnlrmhnletqakgpsb",
		"fbfffrz",
		"ddddd",
		"lyqavutgbwiehjrcqcragbvihujlowtpytzyjhawliuvbqdrmgcrglvzjtuidbcywqamh",
		"edolzsluoeshd",
		"vvvgvv",
		"scwuqekdbmarfiynzoxvptg",
		"ycpvjeubrazgiodxtwncptzsxjmklyvdeaonbqiwr",
		"kbmqslrvnyzpjslxfnbqpjyjsypwbnlq",
		"xvoxvxvvx",
		"ulzdrzoshulrxduzrzrqjutzurvebgc",
		"vpv",
		"nfnnn",
		"bmpfnxzsajwvyhqldrecoutrvnpsoxzlcmeufthkjayqhozncuervmgqpyfatjxlsovrxesptqajlzycfnmhu",
		"lfjcfcfcfc",
		"jdhrxjranxydbgt",
		"yyyyy",
		"tpfydjeejpdfyjyepdfepjdyf",
		"bgphfeuvkcjza",
		"glyxujgjulxh",
		"ubmeofqsxdangrchivyyhcueqvgfasordxmb",
		"vbtexubenvxzkttxbvae",
		"yoxbbyoexobxky",
		"vxhroygampneuzslckibfqdjjqfcvnaizeluhkmrdxpyeidxrkcnvjzhpqymaulf",
		"dtlpjkfarsjtprafdyelafpgjtvlr",
		"zb",
		"rwutpgkyanmnwatgkmpuyr",
		"jbbjjbbjjb",
		"yvcbscsvybhbsvycucsjrinybgpvyhsvbocw",
		"tapdxjkbuhnuqoaigmtphcfv",
		"gbrfbgrfgrfbbrfgrfbg",
		"lhjr",
		"nsuvrrntusrnmdcsunusrusnvr",
		"mglncfrspjxqdheatkbyawokdbmlvurnzjecqsyxpth",
		"dkphrovicboihkdcrvpbkcdvhbiporichrbdpvokprckhibvod",
		"obaxmnutotabunhaobdtunpvfnztekujcbqyoatibmhoagun",
		"mvhtqgsxcztljokabwnitdyuefmqrp",
		"gdxjnxkx",
		"bwfpeojrtnqmszhyajfduwroxmenzhkymhfrjediyznwclokvhfjirnwymekgzo",
		"bzcpqiipcqbhciqpb",
		"vbnegldqebgvqequxgbv",
		"pmcjwzqsrgyesvhujyprdftbpjsnaryoonsrpjy",
		"dfqbynoxcgljpuhaesmvtdxhecqampgnyultfjosvbcifqxleudmvjhgaspybotnsnqvtgaphyfloxeucbdjmayetuxbogqcmfnsjvhpld",
		"woqjbvaesrhrmjaeswobqvrqeswbjoavowebqrvajs",
		"fsgejtjskg",
		"obzeufrsykvjdqgjqaiozpwrmbsdxkfsjqdzfktbrlho",
		"awqldosnzykcdolsawqnczwodsqznacl",
		"ohtxrakybsecjnqviwduzmwodbqsxihrajpcztygluknfve",
		"mmvamqm",
		"ahoubdnlywcigjtcynbhdivwtoglaju",
		"bpgewxzxpubsdwq",
		"adhjekztzjkdeewkvzjdtvefjzdkejdkz",
		"uetkosjndqgxcyvmmclnrsaxjytqvdpg",
		"kbheddixafdtd",
		"xhdhgrd",
		"rbyavgzjflhdinqesksnkvihbalfryjzeqzhaivknreqfjsblybrkljfziyensvaqh",
		"bokdlygwhafrcxwuronlpakqi",
		"pnwsxhpnrwsxh",
		"yhrqpsbjvdaviwuoxlgfc",
		"hwgeihwejbsvzneltwyrhfkaomewxjvh",
		"oxnscztqjyafrhyxnkjvwrufcmpmcgrnulkfjvxyberfkxyucijnwencyxrfhlj",
		"kilhnpjvdofbatczrhgvxiwmncfezvizhucnqfecnhzivfu",
		"umxzfpvkbvpkxumbzfxzkvmfbpuuxkfzvmpbpfxvbumzk",
		"vmsdxahqipznufupiasyvlnxjzdrhqunhagxpkvdsqzie",
		"vdwybvyudwbcdywvuydvwvwjdayh",
		"ddd",
		"qlfcbhrvwfzrbyuc",
		"jcsonkuckosnkcsno",
		"sawivomioasaois",
		"weluyoqhcprdvgsbkwuyuzynjenajxiue",
		"xbrfmeznhowjtbycldqagkuivcbs",
		"uzgpwofxcaqidhntlmboidfhxgbnluzwmcptqtquhizxngoacdwfpmlldztycveqghipmxsnfowuj",
		"nqn",
		"fqudf",
		"cxpvzgfyijsaoltueqkmajuxlvozygsfqpteicmkozeafkvtlqipjugyxsmc",
		"zczrz",
		"jsapzgufkmwvdibqtaerhpisyudxgmvwbjopvnudbctjgfwialms",
		"auylqgmpcfbkiheszzislkfqgapebchfleshzgkqbaipchpnszqkiatefclbwgesxlhdzvbfwkpagqci",
		"jxx",
		"vcypdnoblkfabxwwjqbigibzmkb",
		"hkodlmsgqbzjevcfayivfyticqwblkjsuagdpozmeifdqbksjrxlegomhnczvya",
		"bktgaefprexytwau",
		"xwasezkctrovpcsxbrzhdtw",
		"gzkcdewablmdxyftvqsidhur",
		"kbvzwsdcnpkbszvw",
		"jsvouxkeqgziadrbyz",
		"zvqpbkanyjwgtueflcdrxcpyqrwgtjafuklzxndebvwzdgljoaycekvbptuqxnfirdjrguhfbptyxkzceavnlwq",
		"nhqgxmdslvtzpkmqdfluqomrjelwzflbvqmalxmq",
		"smlxpqfhtkszqhlvmqjomlvksqwduyrbsnlim",
		"wpkcvmxuityzqgjdeofbfvkyxbjdumoptiqwgeczpbdvuetqczokmxfgywijzifybkeudwvqgxjmcpot",
		"porctbafwqzedgysxljkhvjxbdhgqkftnyalsopzvwcekozvgtxejlcpdhqsyfawb",
		"obduynsxfdysbxonuffbsoduxnyubycdxnofsbfysonxud",
		"hisvfxaxafax",
		"yolmbo",
		"jotsmhxfqhsbvrolchsgdaozjotyhsuszoh",
		"dzdzdzzdzdk",
		"idykemasftdpu",
		"fbvmunwkreldcyblaqkxzvyimilbvmxjkysqlaiymvoqhbgkvpklbmyg",
		"jvsmlogjgwvmsplo",
		"risldpqblbsiprxobsiprkl",
		"nzcybwkpahyhwcpkznawzhcnpayk",
		"ixfbamninbubinkencbkei",
		"elchnpjkxwtqignljgiceqahbxlcugbexhqjinidxjhmeqclgfnvfqlhcexigndj",
		"vmgcneztlbsqeblzmvcngstngbclszmvet",
		"ckncccc",
		"yezpvwyvlez",
		"hfdtkslevcwnoxzitsfekmdjvclihzwnoetsiwvnzlkfdhocckfotsdnzivhwle",
		"ey",
		"cdbnbcnd",
		"hbupimtkawejgvfzcnoysxzfnkwbpvchoxietmujsygjmehbtwivfznkupxcsgroygomuvnyjhwekscizbtxpfhspzxkncvfitwjguymebo",
		"qjwjrosgjtqjxe",
		"sjsss",
		"sudlgxvitacpyfhkrisuvgfkrchadnjgvqfzrmdihucsakqgrodskhauficv",
		"rqefisluvygnyjotwizfkiayfyifdftyij",
		"alxbdhwiscqqgcjrwezayahwitmqdcu",
		"ddyxld",
		"zwfdsuqcdzcwcszudwhzdlwb",
		"axvvxvxxv",
		"nrwblzfvgh",
		"peelqmzvgfke",
		"ygfkxdjnublaer",
		"jvnnvjjvnvjn",
		"mblaqhitwdvbljivaqxthdw",
		"ddcddd",
		"ed",
		"vjsrljrlvqsebvlsrjlvrsj",
		"cjftaajfcttjcaffjbhatc",
		"dqbfeprkzgvttpbfkdrqgerwaqfedxkpbgt",
		"owbmusnzvgpforgvlwkyxptvpwohgwtgqcovpgpavywoie",
		"gczomkqlvdbnaolduzmgbqvyec",
		"tynrkjlgsqqsnlytrkjgyntgklrsqjtygrlsnkqmj",
		"pyfrutmwbubwnsrfyyfwrspbydvborwf",
		"qlsmcbhhqlmcsgb",
		"cowjnufayrixrqaynwxfcojxogamefhkdjyrvwcntafrznwocyjxcuirsyxfwloajn",
		"htosaubvkdcr",
		"ewyzhgipllwezhbingydpkhpzwmijeyglieythwpglzm",
		"ozjphrbglsirguphzjoyil",
		"boru",
		"ritlagqevsitslgawgvjsalitruixaolkghst",
		"pnjoxwlurzkytdcbjucwnytzoxbrpldklxpboczwtduykjrnpyzkdnxoljvurwbctrzupcbnxkwoytljd",
		"snpvyotqzxubardqorubpavdnxytzstxpvazrqubnydosvaotxpszyurbgnqdpzxurabtqsvnoyd",
		"wcybutsgnvxlpdjrmekoursvnedtgjbylckqwoxm",
		"otaccototctoc",
		"npndtfblp",
		"uvaeirsyvryjispmsmuiryfzdbyqsrtigrwkmycveis",
		"jhutgyvjuyhtgytuhjghutgyjtuhjyg",
		"zxwyodcmdwzyomcwmdoczywxymojzdcylowdcmvbgz",
		"tjefadyokb",
		"akbwzocshvukchubzawyvoszbwukohvqaschzkbucowsavzykvhoauwbsc",
		"qsyjqpq",
		"bnkryxpdvswjagzhfqtilkgfawvzjinumhldqpytxrb",
		"yfdryfrdroyfddryf",
		"wsvptxyhcqfafysovtqwxchpavahfqtpsywxcwfqaptcsvhyx",
		"wezkdnqhgufvarycxijlobsrzoicqxglbfhenksjwvgwikzclbvrxsnjfoheqhwexrfocgnjvqbzklsi",
		"dmyk",
		"xyqbncxypnshkgylf",
		"mhqunicomchiohciwosm",
	}
}

func getDay06DataPart2() []string {
	return getDataFromFile("day06")
}
